swagger: "2.0"
info:
  title: "API de Usuários"
  description: >
    Documentação da API de Usuários
  version: "1.0.0"
host: "localhost:3333"
schemes:
  - "http"
paths:
  /user/create-user:
    post:
      tags:
        - "User"
      summary: "Cria um usuário"
      description: "Cria um usuário com as informações fornecidas"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: "body"
          description: "Informações do usuário a ser criado"
          required: true
          schema:
            type: "object"
            properties:
              email:
                type: "string"
              name:
                type: "string"
              age:
                type: "integer"
      responses:
        201:
          description: "Usuário criado com sucesso"
        400:
          description: "Campo não recebido"
        422:
          description: "O valor de idade é inválido"
        500:
          description: "Email já cadastrado"
  /user/read-user:
    get:
      tags:
        - "User"
      summary: "Lê um usuário"
      description: "Lê as informações de um usuário com o ID fornecido"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "query"
          description: "ID do usuário a ser lido"
          required: false
          type: "string"
      responses:
        200:
          description: "Informações do usuário lido"
        400:
          description: "Erro na leitura do usuário"
        500:
          description: "Erro interno no servidor"
  /user/update-user:
    patch:
      tags:
        - "User"
      summary: "Atualiza um usuário"
      description: "Atualiza as informações de um usuário com o ID fornecido"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "query"
          description: "ID do usuário a ser atualizado"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          description: "Novas informações do usuário"
          required: true
          schema:
            type: "object"
            properties:
              email:
                type: "string"
              name:
                type: "string"
              age:
                type: "integer"
      responses:
        200:
          description: "Usuário atualizado com sucesso"
        400:
          description: "Erro na atualização do usuário"
        500:
          description: "Erro interno no servidor"
  /user/delete-user:
    delete:
      tags:
        - "User"
      summary: "Remove um usuário"
      description: "Remove o usuário com o ID fornecido"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "query"
          description: "ID do usuário a ser removido"
          required: true
          type: "string"
      responses:
        200:
          description: "Usuário removido com sucesso"
        400:
          description: "Erro na remoção do usuário"
        500:
          description: "Erro interno no servidor"
